language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master
    - release

notifications:
  email: false

sudo: required
dist: trusty

addons:
  firefox: "38.0.5"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16"

before_script:
  - "export DISPLAY=:99.0"
  - tar -xjf /tmp/firefox-38.0.5.tar.bz2 --directory $TRAVIS_BUILD_DIR/
  - export PATH="$TRAVIS_BUILD_DIR/firefox:$PATH"
  - gem install gist

install: true
script:
  - ./gradlew
